### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ligi** [aashrairavooru/Skittles#22]
with wild clicking on the skittle example I could produce this crash on emulator sdk 23 with last commit on masterr 3d6cf49a6b4716ce42a2ba865d25cf214a9b0f94:

```
02-17 04:42:13.868  2884  2884 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at java.util.ArrayList.get(ArrayList.java:310)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at snow.skittles.SkittleAdapter$SkittleViewHolder.onClick(SkittleAdapter.java:160)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at android.view.View.performClick(View.java:5198)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:21147)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:739)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5417)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-17 04:42:13.868  2884  2884 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-17 04:42:13.869  1588  1968 W ActivityManager:   Force finishing activity snow.skittlessample/.MainActivity3

```

**Comment by ghost** [comment]
This happened after wild clicking on the main skittle?

**Comment by jcaruso001** [comment]
I am getting this error when I attempt to close the menu after a menu item is clicked in the onSkittleClick. Can we look into a resolution for this aashrairavooru?

**Comment by jcaruso001** [comment]
FYI this also only happen intermittently, if i do a fresh rebuild most of the time the error goes away.
